name: Push-to-EC2

on:
  push:
    branches:
      - development  # Triggers on push to development branch

jobs:
  deploy:
    name: Deploy to EC2 on development branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          TARGET: ${{ secrets.EC2_TARGETDIR }}

      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/html/greymarket-newTheam
            git pull origin development
            npm install
            npm run build
            pm2 restart Graymarket-IPO || pm2 start npm --name "Graymarket-IPO" -- start -- -p 5173